name: nerfmeshes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch=1.6.0
  - torchvision=0.7.0
  - cudatoolkit=10.2  # Cambia in 11.0/CPU se necessario
  - pip:
      - absl-py==0.10.0
      - cachetools==4.1.1
      - certifi==2020.6.20
      - chardet==3.0.4
      - cycler==0.10.0
      - decorator==4.4.2
      - future==0.18.2
      - fvcore==0.1.2.post20201016
      - google-auth==1.22.1
      - google-auth-oauthlib==0.4.1
      - grpcio==1.32.0
      - idna==2.10
      - imageio==2.9.0
      - importlib-metadata==2.0.0
      - kiwisolver==1.2.0
      - markdown==3.3.1
      - matplotlib==3.3.3  # Compatibile con Python 3.7
      - networkx==2.5
      - numpy==1.19.2
      - oauthlib==3.1.0
      - opencv-python-headless==4.4.0.44
      - openexr==1.3.2
      - packaging==20.4
      - pillow==8.0.0
      - portalocker==2.0.0
      - protobuf==3.13.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyparsing==2.4.7
      - python-dateutil==2.8.1
      - tensorboard==2.2.0  # Mantengo la versione 2.2.0 richiesta da pytorch-lightning
      - pytorch-lightning==0.9.0
      - pywavelets==1.1.1
      - pyyaml==5.3.1
      - requests==2.24.0
      - requests-oauthlib==1.3.0
      - rsa==4.6
      - scikit-image==0.17.2
      - scipy==1.5.2
      - six==1.15.0
      - tabulate==0.8.7
      - tensorboard-plugin-wit==1.7.0
      - termcolor==1.1.0
      - tifffile==2020.10.1
      - tqdm==4.50.2
      - urllib3==1.25.10
      - werkzeug==1.0.1
      - wheel==0.35.1
      - yacs==0.1.8
      - zipp==3.3.1